import Tractore from './tractor.png';
import Down from './down-arrow-svgrepo-com.png';
import Transparent_Tractore from './tractore-removebg-preview.png';
import Eaneer_Logo from './eaneer logo with text.png';
import Logo from './eaneer logo.png';
import Second_Tractore from './traktor.png';
import Building from './Path 454.png';
import Manufacture from './Group 193.png';
import Something from './Group 191.png';
import About_Us_Image from './Image 1.png';
import About_Us_Image2 from './Mask Group 2.png';
import About_Us_Image3 from './Mask Group 3.png';
import About_Us_Image4 from './Mask Group 4.png';
import Adresse_Contact from './Group 234.png';
import Telephone_Contact from './Group 239.png';
import Email_Contact from './Group 241.png';
import LinkedIn from './LinkedIn.png';
import Facebook from './Facebook.png';
import Instagram from './Instagram.png';
import TikTok from './TikTok.png';
import Mask_Group_7 from './Mask Group 7.png';
import Component23 from './Component 23 – 2.png';
import Partners_Image from './Mask Group 8.png';
import Univers_Image from './Image 5.png';
import Mask_Group_9 from './Mask Group 9.png';
import Mask_Group_10 from './Mask Group 10.png';
import Mask_Group_11 from './Mask Group 11.png';
import Mask_Group_12 from './Mask Group 12.png';
import Path_8 from './Path 8.png';
import Mask_Group_13 from './Mask Group 13.png';
import Mask_Group_14 from './Mask Group 14.png';
import Mask_Group_15 from './Mask Group 15.png';
import Mask_Group_16 from './Mask Group 16.png';
import Mask_Group_17 from './Mask Group 17.png';
import Mask_Group_18 from './Mask Group 18.png';
import Mask_Group_19 from './Mask Group 19.png';
import Mask_Group_20 from './Mask Group 20.png';
import Mask_Group_1 from './Mask Group 1.png';
import Group_225 from './Group 225.png';
import Image_App from './mobile-app.png';
import Mask_Group_22 from './Mask Group 22.png';

export const tractore=Tractore;
export const down=Down;
export const transparent_tractor=Transparent_Tractore;
export const eaneer_logo=Eaneer_Logo;
export const logo=Logo;
export const second_tractore=Second_Tractore;
export const building=Building;
export const manufacture=Manufacture;
export const something=Something;
export const about_us_image=About_Us_Image;
export const about_us_image2=About_Us_Image2;
export const about_us_image3=About_Us_Image3;
export const about_us_image4=About_Us_Image4;
export const adresse_contact=Adresse_Contact;
export const telephone_contact=Telephone_Contact;
export const email_contact=Email_Contact;
export const linkedin=LinkedIn;
export const facebook=Facebook;
export const instagram=Instagram;
export const tiktok=TikTok;
export const mask_group_7=Mask_Group_7;
export const component23=Component23;
export const partners_image=Partners_Image;
export const univers_image=Univers_Image;
export const mask_group_9=Mask_Group_9;
export const mask_group_10=Mask_Group_10;
export const mask_group_11=Mask_Group_11;
export const mask_group_12=Mask_Group_12;
export const path_8=Path_8;
export const mask_group_13=Mask_Group_13;
export const mask_group_14=Mask_Group_14;
export const mask_group_15=Mask_Group_15;
export const mask_group_16=Mask_Group_16;
export const mask_group_17=Mask_Group_17;
export const mask_group_18=Mask_Group_18;
export const mask_group_19=Mask_Group_19;
export const mask_group_20=Mask_Group_20;
export const mask_group_1=Mask_Group_1;
export const group_225=Group_225;
export const image_app=Image_App;
export const mask_group_22=Mask_Group_22;
